spring.application.name=bramwell

spring.datasource.url=jdbc:mysql://localhost:5173/
spring.datasource.username=root
spring.datasource.password=yourpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.password=none
